#!/bin/bash

code --install-extension akamud.vscode-theme-onedark
code --install-extension arcticicestudio.nord-visual-studio-code
code --install-extension batisteo.vscode-django
code --install-extension bungcip.better-toml
code --install-extension christian-kohler.path-intellisense
code --install-extension Dart-Code.dart-code
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.python-environment-manager
code --install-extension donjayamanne.python-extension-pack
code --install-extension eg2.vscode-npm-script
code --install-extension formulahendry.code-runner
code --install-extension golang.go
code --install-extension HookyQR.beautify
code --install-extension KevinRose.vsc-python-indent
code --install-extension magicstack.MagicPython
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.makefile-tools
code --install-extension mshr-h.veriloghdl
code --install-extension naumovs.color-highlight
code --install-extension njpwerner.autodocstring
code --install-extension PKief.material-icon-theme
code --install-extension redhat.java
code --install-extension rust-lang.rust
code --install-extension samverschueren.final-newline
code --install-extension shardulm94.trailing-spaces
code --install-extension SolarLiner.linux-themes
code --install-extension sumneko.lua
code --install-extension teabyii.ayu
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension wavetrace.wavetrace
code --install-extension webfreak.debug
code --install-extension wholroyd.jinja
code --install-extension zhuangtongfa.material-theme
